set(BUILD_MFM_CONVERTER OFF CACHE INTERNAL "")
set(BUILD_GEANT4_SIM OFF CACHE INTERNAL "")
set(BUILD_NPTOOL OFF CACHE INTERNAL "")

set(LILAK_PROJECT_LIST ${LILAK_PROJECT_LIST}
stark
atomx
CACHE INTERNAL ""
)

set(GRU_DIR /usr/local/gru CACHE INTERNAL "")
set(GET_DIR /usr/local/get CACHE INTERNAL "")
set(NPTOOL_NPLIB_LIST ${NPTOOL_NPLIB_LIST}
NPCore
NPPhysics
NPSTARK
NPATOMX
CACHE INTERNAL ""
)
set(LILAK_BIND_LIST ${LILAK_BIND_LIST}

CACHE INTERNAL ""
)

set(NPTOOL_DIR CACHE CACHE INTERNAL "")