#lilak/print  all  # print after init gen:par:out:in:det:task
#lilak/collect_par  print  # file name to write collected parameters. 'print' to print out on screen
#lilak/auto_exit  0  # set(1)/unset(0) auto termination
lilak/run  0  # run [no] after init. Execute all events if [no] is 0
#lilak/draw  0  # execute Draw()
#lilak/execute  0  # execute event [no] after init
lilak/add  LKGETConversionTask  # add task or detector class
lilak/add  LKSetSiChannelTask  # add task or detector class
# Uncomment this block to write calibrated SiChannel energies.
#lilak/add  LKEnergyRestorationTask
#LKEnergyRestorationTask/energyCalibrationFile data_calibration/run_e{CALRUN}/pre_li7_e{CALRUN}.energy_calibration.dat
#LKEnergyRestorationTask/c2ReferenceEnergy  5.486
#LKEnergyRestorationTask/buildSiHit  true

LKRun/Name  pre_li7  # name of the run
#LKRun/RunID  111  # run number
#LKRun/RunID  142  # run number
LKRun/RunID  e{RUN}  # run number
#LKRun/RunID  125  # run number
LKRun/Tag  reco  # tag
LKRun/OutputPath  /Users/jungwoo/data/stark/reco  # path to the output. Default path {lilak_data} is lilak/data/
LKRun/InputPath  /Users/jungwoo/data/stark/raw  # LKRun will search files from input paths when LKRun/SearchRun
LKRun/SearchRun  mfm  # search input files with LKRun/RunID. opt=mfm: search mfm files, opt=[tag]: search run_runNo.*.[tag].root
LKRun/AutoTerminate  true  # automatically terminate root after end of run
#LKRun/Division  0  # division within the run [optional]
#LKRun/InputFile  /Users/jungwoo/data/stark/raw/run_0111.dat.14-05-26_10h19m15s  # input file. Cannot be used with LKRun/SearchRun
#LKRun/FriendFile  to/friend/file  # input friend file
#LKRun/RunIDList  1, 2, 3, 4  # list of run numbers separated by ,
#LKRun/RunIDRange  1, 10  # list of run numbers ranged by ,
#LKRun/EntriesLimit  100000  # limit number of run entries
LKRun/EventCountForMessage  20000
#LKRun/UpdateOutputFile  0  # update root file with option update
#LKRun/FileName  # file name will be fixed to this name if it is not null string

#LKGETConversionTask/InputFileName  /Users/jungwoo/data/stark/raw/run_0111.dat.14-05-26_10h19m15s  # input is provided by LKRun/SearchRun

#si_array/MappingPath mapping_BB10_DepV_Test
si_array/MappingPath e{MAPPING}

persistency/FrameHeader  false  # save branch to output file
persistency/PFData  false  # save branch to output file
persistency/RawData  true  # save branch to output file
persistency/SiChannel  true  # save branch to output file
persistency/SiHit  true  # save branch to output file

LKRun/ElogEnable             true
#LKRun/ElogInitFormatID       <INIT_OF_${system_name}_RUN_FORMAT_ID>
#LKRun/ElogEndFormatID        <END_OF_${system_name}_RUN_FORMAT_ID>
LKRun/ElogTimeout            5
