
#LKSiliconArray/EveThreshold   300  # # threshold for default peak finding method
#LKSiliconArray/EventCountForMessage     2000  # event count for message at event accumulation
#LKSiliconArray/FigurePath     .  # path to save figues
#LKSiliconArray/fillOption     hit  # fill option to fill detector histogram
#LKSiliconArray/jumpEventSize  2000  # jump event value amount when jump event button is clicked
#LKSiliconArray/skipToEnergy   500  # energy to reference when, button(skip to event containing channel with pulse height>energy) is clicked

persistency/PFData            true
persistency/SiChannel         true

#si_array/ForceMapping
si_array/Mapping1               # name of detector mapping file
si_array/Mapping2               # name of channel mapping file
si_array/MappingPath            # name of silicon mapping directory or detector mapping file

stark/pulseFile
